server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
spring:
  rabbitmq:
    host: SERVER_HOST
    port: 5672
    username: root
    password: 12345678
    virtual-host: /
  sleuth:
    enabled: false
  zipkin:
    enabled: false
logging:
  level:
    org.springframework.cloud.openfeign: error
    org.springframework.cloud.bus: error
    com.scott.neptune: error
