server:
  port: 8769
eureka:
  client:
    serviceUrl:
      defaultZone: http://scott:12345678@localhost:8761/eureka/
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: 12345678
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
  mail:
    protocol: smtp
    host: smtp.163.com
    username: xxxxxxxx@163.com
    password: 12345678
    default-encoding: UTF-8
logging:
  level:
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.bus: debug
    com.scott.neptune: debug