eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: user
  messages:
    basename: i18n/messages
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
#  session:
#    store-type: redis
#    timeout: 2000
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 20000
    jedis:
      pool:
        max-active: 0
        max-wait: -1
        max-idle: 8
        min-idle: 0
  datasource:
    url: jdbc:mysql://localhost:3306/db_neptune_blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: scott
    password: liu762327610
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#  devtools:
#    restart:
#      enabled: true
#    livereload:
#      enabled: true