server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
  redis:
    host: serverhost
    port: 6379
    database: 0
    timeout: 20000
    jedis:
      pool:
        max-active: 0
        max-wait: -1
        max-idle: 8
        min-idle: 0
  rabbitmq:
    host: serverhost
    port: 5672
    username: scott
    password: 12345678
    virtual-host: /
  sleuth:
    sampler:
      probability: 0
zuul:
  #  sensitiveHeaders: "*"
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
    connection-request-timeout-millis: 20000
hystrix:
  shareSecurityContext: true
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
  eager-load:
    enabled: true
logging:
  level:
    org.springframework.cloud.openfeign: error
    org.springframework.cloud.bus: error
    com.scott.neptune: error