version: '3.1'

services:
  minio:
    image: minio/minio
    container_name: minio
    command: server /data
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: scott
      MINIO_SECRET_KEY: 12345678
    volumes:
      - /Users/scott/Data/docker/minio/data:/data