version: '3.1'

services:
  mysql:
    image: mysql:8.0.17
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    # restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - /Users/scott/Data/docker/mysql/data:/var/lib/mysql