version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.7.16-management-alpine
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=scott
      - RABBITMQ_DEFAULT_PASS=12345678
    #restart: always
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - /Users/scott/Data/docker/rabbitmq/data:/var/lib/rabbitmq
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"