spring:
  profiles:
    active: dev
  application:
    name: search-server
  messages:
    basename: i18n/messages
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
#  cloud:
#    config:
#      discovery:
#        enabled: true
#        service-id: config-server
#      override-none: false
#      fail-fast: true
#      name: ${spring.application.name}
#      profile: ${spring.profiles.active}
feign:
  hystrix:
    enabled: true
eureka:
  instance:
    prefer-ip-address: true