server:
  port: 8761

spring:
  application:
    name: eurka-client

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#  register-with-eureka: false
#  client:
#    enable-self-preservation: false