spring:
  application:
    name: config-server
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/liuweigeek/NeptuneBlog-config-repo.git
          #uri: https://github.com/liuweigeek/NeptuneBlog-config-repo.git
          search-paths: repo
          basedir: config-server/target/config
management:
  server:
    servlet:
      context-path: /admin
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    web: TRACE
    org.springframework.web: TRACE