server:
  port: 8090
spring:
  rabbitmq:
    host: SERVER_HOST
    port: 5672
    username: scott
    password: 12345678
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true